name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gradle.properties
        env:
          GITHUB_USER: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        shell: bash
        run: |
          touch gradle.properties
          echo gpr.user = ${GITHUB_USER} >> gradle.properties
          echo gpr.key = ${GITHUB_TOKEN} >> gradle.properties
          echo kotlin.code.style=official >> gradle.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build
        run: ./gradlew build